### ISSUE TITLE
Week 05 - Day 3 - Thanksgiving Break Assignment

### ISSUE THREAD

**Issue by gstark** [mmyenny/Assignments#17]
# Choose one or more of the following:
- Try the [Javascript Koans](https://github.com/suncoast-devs/koans)
- Implement Blackjack in React
- Implement Tic-Tac-Toe in React
- Implement [this homework](https://suncoast.io/handbook/curriculum/front-end/react-ii/assignments/snowman/)
- Go through the free [Javascript 30](https://javascript30.com)

# Videos to Watch
- Watch this [amazing video](https://vimeo.com/36579366)

**Comment by mmyenny** [comment]
https://github.com/mmyenny/koans

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Yas](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb161dfb00865249fe33bc4a730793f1eef22b19/neil.gif)
> &ldquo;Yas&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/3)**__
